### PR TITLE
fix(lexer): handle unary minus operator

### LINKED ISSUE #258: 🐞  Dex modifier breaking the Initiative tracker with Dice roller on
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

dice roller + fantasy statblocks + initiative tracker works fine for all creatures.

### Current behaviour

Enabling dice roller with the fantasy statblocks and initiative tracker ruins the start combat with creatures with DEX < 10.

### Reproduction

Install all the three mods, try to go to "Initiative tracker encounter builder" and add a creature like Zombie from the SRD. It won't work unless you disable the dice roller. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

10.1.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

Probably the reason is the negative dex modifier to the initiative. However, simply setting the formula in initiative calculation to "4" did not work so it appears like the reason is somewhere deeper.

I found this while making custom mobs using YAML in fantasy statblock and debugged it up to this point. All the plugins are up to date to the current date.

### PR DESCRIPTION
**Pull request by twiescha**
add tests for lexer

## Pull Request Description

formulas with non leading unary minus signs threw exceptions, e.g "1d20 + -2"
this should be fixed

See:
fixes #258

### CODE REVIEW

File: src/parser/lexer.ts [hunk 1]
```diff
@@ -142,18 +143,44 @@ export default class Lexer {
...
+                    if (isPlusOrMinus(top) && isPlusOrMinus(e)) {
+                        if (isMinus(top) != isMinus(e)) {
+                            // one minus => minus
+                            if (!isMinus(top))
+                                replaceTop(acc, e)
+                        } else {
+                            // plus
+                            if (isMinus(top)) {
+                                let newTop = copy(top)
+                                newTop.type = newTop.type === "math" ? newTop.type : "+"
```
Comment (valentine195) [inline src/parser/lexer.ts:170]: You can just modify top directly, instead of replacing it in-place.

**Review by valentine195 — APPROVED** [review]
